### ISSUE TITLE
ipadic-mecab-2_7_0-small is broken

### ISSUE THREAD

**Issue by vbkaisetsu** [daac-tools/vibrato#117]
The second feature of the unknown word dictionary is not pronunciation.
![Screenshot from 2023-02-04 15-34-52](https://user-images.githubusercontent.com/2175479/216752956-4e6c8b98-f5ad-4369-8276-374ba72fbd7c.png)

**Comment by kampersanda** [comment]
@vbkaisetsu Thank you for the report. I forgot to update the unknow dictionary. I'll address it ASAP.

**Comment by kampersanda** [comment]
@vbkaisetsu 

I updated https://github.com/daac-tools/vibrato/releases/download/v0.4.0/ipadic-mecab-2_7_0-small.tar.xz to handle `pron` for unknown words as empty.

Could you try this and, if ok, deploy it?

![スクリーンショット 2023-02-04 18 21 43](https://user-images.githubusercontent.com/15042374/216759787-97e8c60f-edb1-4ac5-9b87-b628b5fc07b0.png)

**Comment by vbkaisetsu** [comment]
Deployed. Thanks
