### ISSUE TITLE
65535を超える文字で分かち書きできない。

### ISSUE THREAD

**Issue by saito-kosuke** [daac-tools/vibrato#127]
**バグの説明**
65535を超える文字で分かち書きできません。

**再現手順**
(誰もが同じ状況を再現できるように、 `git clone` コマンドを含め、すべてのコマンドを記述してください。)
以下のコードを実行しました:
textが65535を超える文字数の場合、100%再現します。
```
let mut worker = tokenizer.new_worker();
worker.reset_sentence(&text);
worker.tokenize();
```
以下のメッセージが出力されました:
thread 'main' panicked at 'assertion failed: input.len() <= 0xFFFF', /Users/saitoukosuke/.cargo/registry/src/github.com-1ecc6299db9ec823/vibrato-0.4.0/src/dictionary/lexicon/map/trie.rs:53:9

**期待する結果**
(期待した出力を明確かつ簡潔に記述してください。)
65535を超える文字数でも分かち書きできるようにしたいです。
https://github.com/daac-tools/vibrato/blob/main/vibrato/src/dictionary/lexicon/map/trie.rs#L53
を外せばうまくいくと思われますが、制限を付けている理由があるようでしたら、このままの仕様で構いません。

**あなたの実行環境**
 - OS: [e.g. Ubuntu 22.04] mac big sur
 - Rust: [e.g. 1.64.0] 1.67.1

**Comment by vbkaisetsu** [comment]
recurrence: https://github.com/daac-tools/vibrato/issues/70

**Comment by vbkaisetsu** [comment]
@saito-kosuke ご報告ありがとうございます。

以前のバージョンでは入力の長さに制限があり、ご指摘の `debug_assert!()` の箇所でアサーションを行っていました。
#72 で長さ制限が撤廃されたのですが、修正の不備によりデバッグモードで入力の長さを確認する状態になっていました。
修正パッチを書いたので、マージされるまでお待ちください。

**Comment by saito-kosuke** [comment]
@vbkaisetsu 
早速ありがとうございます！
