### ISSUE TITLE
The difference between Vibrato and Vaporetto regarding the performance for a general tokenizing 

### ISSUE THREAD

**Issue by saito-kosuke** [daac-tools/vibrato#135]
**Is your feature request related to a problem? Please describe.**

I'd like to know the difference between Vibrato and Vaporetto regarding the performance for a general tokenizing as follows.
https://github.com/daac-tools/vibrato#fast-tokenization

**Describe the solution you'd like**

Could you add Vaporetto to the following image?
https://github.com/daac-tools/vibrato#fast-tokenization

**Describe alternatives you've considered**

Nothing

**Additional context**

Nothing

**Comment by vbkaisetsu** [comment]
@saito-kosuke Since Vibrato is intended to be MeCab compatible, which employs the lattice method, and is used for different purposes than Vaporetto and KyTea, which employs the pointwise prediction method, a simple comparison cannot be made.

However, I think it is possible to show a comparison between Vibrato and Vaporetto if we are careful to avoid misunderstandings.

@kampersanda What do you think?

**Comment by saito-kosuke** [comment]
@vbkaisetsu Thank you for your answer. The comparison would make it clear for us to understand the use cases of each service further.

**Comment by kampersanda** [comment]
@saito-kosuke [Our wiki page](https://github.com/daac-tools/vibrato/wiki/Speed-Comparison) provides comparison results with Vaporetto. Shortly, Vaporetto with a KyTea model was 2x faster than Vibrato with IPADIC. (However, we do not put the result on the top page to avoid misunderstandings from their different purposes, as @vbkaisetsu said).

Another result can be found in [our Japanese blog post](https://tech.legalforce.co.jp/entry/2022/09/20/133132).

The following repository is the actual code used for the benchmark.
https://github.com/legalforce-research/tokenizer-speed-bench

**Comment by saito-kosuke** [comment]
@kampersanda That makes sense. Thank you for your reply.

**Comment by kampersanda** [comment]
I have closed this issue as it seems to have been resolved.

**Comment by kirawi** [comment]
What is the difference between the different libraries? Is one more accurate than the other?
