### ISSUE TITLE
Take `BufRead` as arguments

### ISSUE THREAD

**Issue by kampersanda** [daac-tools/vibrato#32]
First, see https://github.com/daac-tools/vibrato/pull/31#discussion_r956692630.

Here, I consider the two options:

- Keep `Read` and removes the Notes section.
- Fix `csv` crate to take the `BufRead` argument and use `BufRead` through all arguments.

**Comment by kampersanda** [comment]
It seems easy to modify the `csv` crate to use `BufRead`.
I think the second option is better, and I will do that.

@vbkaisetsu What do you think?

**Comment by vbkaisetsu** [comment]
The first option would be better for convenience.

> modify the `csv` crate

Is this possible?
Narrowing the trait boundaries is unacceptable to many users.

**Comment by kampersanda** [comment]
> Is this possible?

This can be done if I fork `csv` and update the implementation.

> Narrowing the trait boundaries is unacceptable to many users.

Does it mean `Read` is easier to use than `BufRead` (for users)?

**Comment by vbkaisetsu** [comment]
Ofcourse Read is easier for users because the BufRead trait requires Read.

**Comment by vbkaisetsu** [comment]
I don't see the benefit of forking the csv crate just to make the argument BufRead.

**Comment by vbkaisetsu** [comment]
I think that taking both Read and BufRead is not a bad option.

**Comment by kampersanda** [comment]
> I don't see the benefit of forking the csv crate just to make the argument BufRead.

I fear that handling `Read` and `BufRead` in the same function may be a bit confusing (https://github.com/daac-tools/vibrato/pull/31#discussion_r956844555m). Even if we replace `C` and `P` with `BufRead` in [Dictionary::from_readers](https://docs.rs/vibrato/latest/vibrato/dictionary/struct.Dictionary.html#method.from_readers), there remains the fact that there is no need to wrap `S` and `U` of `Read` in a buffered reader. To apply `BufRead` to `S` and `U`, it is necessary to fix the `csv` crate.

> I think that taking both Read and BufRead is not a bad option.

I think the first option that keeps `Read` is the best because the API is easy to understand.
