### ISSUE TITLE
Support text longer than 65535 characters

### ISSUE THREAD

**Issue by vbkaisetsu** [daac-tools/vibrato#43]
Currently, Vibrato does not support texts longer than 65535 characters.
The limit is specified here:
https://github.com/daac-tools/vibrato/blob/de250202a8abede9e761b4e169f904dd5f1c2661/vibrato/src/common.rs#L16

This limit is long enough to parse a typical sentence but should be changed to a larger value, such as 2^32-1, to increase robustness in actual operations.

**Comment by vbkaisetsu** [comment]
@kampersanda The maximum length is 65534, not 65535.
```
$ python3 -c "print('a' * 65536)" | cargo run --release -p tokenize -- -Owakati -i ./model.bin > /dev/null
Loading the dictionary...
Ready to tokenize
Error: InvalidArgument(InvalidArgumentError { arg: "input", msg: "An input sentence must not have a length no more than 65535" })

$ python3 -c "print('a' * 65535)" | cargo run --release -p tokenize -- -Owakati -i ./model.bin > /dev/null
Loading the dictionary...
Ready to tokenize
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', vibrato/src/tokenizer/lattice.rs:73:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ python3 -c "print('a' * 65534)" | cargo run --release -p tokenize -- -Owakati -i ./model.bin > /dev/null
Loading the dictionary...
Ready to tokenize
```

**Comment by kampersanda** [comment]
@vbkaisetsu Thank you for your report. I created another bug issue https://github.com/daac-tools/vibrato/issues/70 because the bug issue is different from the objective of this issue.
