### ISSUE TITLE
Keep an easy description in the top-level readme

### ISSUE THREAD

**Issue by kampersanda** [daac-tools/vibrato#68]
This issue proposes to maintain command line tools related to training in one workspace and put the description of training under the workspace (like `prepare`) for keeping an easy description in the top-level readme. 

## Why

For many light users, the primary concern would be how to get started on tokenization using Vibrato. So, I think the top-level readme should keep an easy description.

The description of `3. Training` in Section `Basic usage` is for advanced users because to understand this, it is necessary to know the configuration of dictionary files in MeCab.

Also, maintaining multiple workspaces increases the costs of updating dependencies in `Cargo.toml`.

## Solution

We keep the command line tools `train`, `dictgen`, `evaluate`, and `split` in one workspace (such as named `train`) and write the usage in the readme under this workspace.

## Benefits

- Descriptions related to training are maintained in a single document, allowing for leading only advanced users there.
- Fewer workspaces can be maintained, resulting in avoiding redundant update costs of `Cargo.toml`.

**Comment by kampersanda** [comment]
@vbkaisetsu What do you think about this proposal?

**Comment by kampersanda** [comment]
Note: My first priority is to keep an easy description in the top-level readme for many light users. Maintaining several command line tools in a single workspace is the second priority. Thus, another solution is to maintain documents for advanced users in a second-level directory (such as named `doc`).

**Comment by vbkaisetsu** [comment]
I agree with moving some commands under `train`.
